// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chains.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChainAssociation = `-- name: CreateChainAssociation :one
INSERT INTO job_chain_associations (
    job_id,
    rank_id,
    chain_id,
    state,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    'ACTIVE',
    $4
)
RETURNING job_id, rank_id, chain_id, state, created_at, draining_at
`

type CreateChainAssociationParams struct {
	JobID   uuid.UUID          `json:"job_id"`
	RankID  uuid.UUID          `json:"rank_id"`
	ChainID int64              `json:"chain_id"`
	DbTime  pgtype.Timestamptz `json:"db_time"`
}

func (q *Queries) CreateChainAssociation(ctx context.Context, arg CreateChainAssociationParams) (JobChainAssociation, error) {
	row := q.db.QueryRow(ctx, createChainAssociation,
		arg.JobID,
		arg.RankID,
		arg.ChainID,
		arg.DbTime,
	)
	var i JobChainAssociation
	err := row.Scan(
		&i.JobID,
		&i.RankID,
		&i.ChainID,
		&i.State,
		&i.CreatedAt,
		&i.DrainingAt,
	)
	return i, err
}

const deleteDrainingChainAssociation = `-- name: DeleteDrainingChainAssociation :execrows
DELETE FROM job_chain_associations
WHERE job_id = $1
  AND rank_id = $2
  AND chain_id = $3
  AND state = 'DRAINING'
`

type DeleteDrainingChainAssociationParams struct {
	JobID   uuid.UUID `json:"job_id"`
	RankID  uuid.UUID `json:"rank_id"`
	ChainID int64     `json:"chain_id"`
}

func (q *Queries) DeleteDrainingChainAssociation(ctx context.Context, arg DeleteDrainingChainAssociationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDrainingChainAssociation, arg.JobID, arg.RankID, arg.ChainID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDrainingChainAssociations = `-- name: ListDrainingChainAssociations :many
SELECT job_id, rank_id, chain_id, state, created_at, draining_at
FROM job_chain_associations
WHERE state = 'DRAINING'
  AND (
      NOT $1::boolean
      OR (job_id, rank_id, chain_id) > (
          $2::uuid,
          $3::uuid,
          $4::bigint
      )
  )
ORDER BY job_id, rank_id, chain_id
LIMIT $5
`

type ListDrainingChainAssociationsParams struct {
	HasCursor    bool      `json:"has_cursor"`
	AfterJobID   uuid.UUID `json:"after_job_id"`
	AfterRankID  uuid.UUID `json:"after_rank_id"`
	AfterChainID int64     `json:"after_chain_id"`
	ResultLimit  int32     `json:"result_limit"`
}

func (q *Queries) ListDrainingChainAssociations(ctx context.Context, arg ListDrainingChainAssociationsParams) ([]JobChainAssociation, error) {
	rows, err := q.db.Query(ctx, listDrainingChainAssociations,
		arg.HasCursor,
		arg.AfterJobID,
		arg.AfterRankID,
		arg.AfterChainID,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobChainAssociation{}
	for rows.Next() {
		var i JobChainAssociation
		if err := rows.Scan(
			&i.JobID,
			&i.RankID,
			&i.ChainID,
			&i.State,
			&i.CreatedAt,
			&i.DrainingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAllJobChainAssociations = `-- name: LockAllJobChainAssociations :many
SELECT job_id, rank_id, chain_id, state, created_at, draining_at
FROM job_chain_associations
WHERE job_id = $1
ORDER BY rank_id, chain_id
FOR UPDATE
`

func (q *Queries) LockAllJobChainAssociations(ctx context.Context, jobID uuid.UUID) ([]JobChainAssociation, error) {
	rows, err := q.db.Query(ctx, lockAllJobChainAssociations, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobChainAssociation{}
	for rows.Next() {
		var i JobChainAssociation
		if err := rows.Scan(
			&i.JobID,
			&i.RankID,
			&i.ChainID,
			&i.State,
			&i.CreatedAt,
			&i.DrainingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChainAssociations = `-- name: LockChainAssociations :many
WITH input AS (
    SELECT
        $2::uuid[] AS rank_ids,
        $3::bigint[] AS chain_ids
),
requested AS (
    SELECT
        rank.rank_id,
        input.chain_ids[rank.ordinality] AS chain_id
    FROM input,
         unnest(input.rank_ids) WITH ORDINALITY AS rank (rank_id, ordinality)
)
SELECT association.job_id, association.rank_id, association.chain_id, association.state, association.created_at, association.draining_at
FROM job_chain_associations AS association
JOIN requested USING (rank_id, chain_id)
WHERE association.job_id = $1
ORDER BY association.rank_id, association.chain_id
FOR UPDATE OF association
`

type LockChainAssociationsParams struct {
	JobID    uuid.UUID   `json:"job_id"`
	RankIds  []uuid.UUID `json:"rank_ids"`
	ChainIds []int64     `json:"chain_ids"`
}

func (q *Queries) LockChainAssociations(ctx context.Context, arg LockChainAssociationsParams) ([]JobChainAssociation, error) {
	rows, err := q.db.Query(ctx, lockChainAssociations, arg.JobID, arg.RankIds, arg.ChainIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobChainAssociation{}
	for rows.Next() {
		var i JobChainAssociation
		if err := rows.Scan(
			&i.JobID,
			&i.RankID,
			&i.ChainID,
			&i.State,
			&i.CreatedAt,
			&i.DrainingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChainDraining = `-- name: MarkChainDraining :one
UPDATE job_chain_associations
SET state = 'DRAINING',
    draining_at = $1
WHERE job_id = $2
  AND rank_id = $3
  AND chain_id = $4
  AND state = 'ACTIVE'
RETURNING job_id, rank_id, chain_id, state, created_at, draining_at
`

type MarkChainDrainingParams struct {
	DbTime  pgtype.Timestamptz `json:"db_time"`
	JobID   uuid.UUID          `json:"job_id"`
	RankID  uuid.UUID          `json:"rank_id"`
	ChainID int64              `json:"chain_id"`
}

func (q *Queries) MarkChainDraining(ctx context.Context, arg MarkChainDrainingParams) (JobChainAssociation, error) {
	row := q.db.QueryRow(ctx, markChainDraining,
		arg.DbTime,
		arg.JobID,
		arg.RankID,
		arg.ChainID,
	)
	var i JobChainAssociation
	err := row.Scan(
		&i.JobID,
		&i.RankID,
		&i.ChainID,
		&i.State,
		&i.CreatedAt,
		&i.DrainingAt,
	)
	return i, err
}
