// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chunks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignChunk = `-- name: AssignChunk :one
UPDATE chunks
SET state = 'LEASED',
    current_rank_id = $1,
    current_chain_id = $2,
    lease_generation = lease_generation + 1,
    lease_expires_at = $3,
    retry_count = $4,
    not_before = NULL,
    last_failure_class = CASE
        WHEN $5::boolean THEN 'LEASE_EXPIRED'
        ELSE last_failure_class
    END,
    last_failure_message = CASE
        WHEN $5::boolean THEN 'active chain lease expired'
        ELSE last_failure_message
    END,
    last_failure_at = CASE
        WHEN $5::boolean THEN $6
        ELSE last_failure_at
    END,
    updated_at = $6
WHERE job_id = $7
  AND chunk_id = $8
RETURNING job_id, chunk_id, input_ref, state, current_rank_id, current_chain_id, lease_generation, lease_expires_at, retry_count, not_before, output_uri, output_checksum, output_size_bytes, last_failure_class, last_failure_message, last_failure_at, created_at, updated_at, terminal_at
`

type AssignChunkParams struct {
	RankID           pgtype.UUID        `json:"rank_id"`
	ChainID          *int64             `json:"chain_id"`
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	RetryCount       int32              `json:"retry_count"`
	RecordExpiration bool               `json:"record_expiration"`
	DbTime           pgtype.Timestamptz `json:"db_time"`
	JobID            uuid.UUID          `json:"job_id"`
	ChunkID          int64              `json:"chunk_id"`
}

func (q *Queries) AssignChunk(ctx context.Context, arg AssignChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, assignChunk,
		arg.RankID,
		arg.ChainID,
		arg.LeaseExpiresAt,
		arg.RetryCount,
		arg.RecordExpiration,
		arg.DbTime,
		arg.JobID,
		arg.ChunkID,
	)
	var i Chunk
	err := row.Scan(
		&i.JobID,
		&i.ChunkID,
		&i.InputRef,
		&i.State,
		&i.CurrentRankID,
		&i.CurrentChainID,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NotBefore,
		&i.OutputUri,
		&i.OutputChecksum,
		&i.OutputSizeBytes,
		&i.LastFailureClass,
		&i.LastFailureMessage,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const cancelNonterminalChunks = `-- name: CancelNonterminalChunks :execrows
UPDATE chunks
SET state = 'CANCELLED',
    current_rank_id = NULL,
    current_chain_id = NULL,
    lease_expires_at = NULL,
    not_before = NULL,
    terminal_at = $1,
    updated_at = $1
WHERE job_id = $2
  AND state IN ('READY', 'LEASED')
`

type CancelNonterminalChunksParams struct {
	DbTime pgtype.Timestamptz `json:"db_time"`
	JobID  uuid.UUID          `json:"job_id"`
}

func (q *Queries) CancelNonterminalChunks(ctx context.Context, arg CancelNonterminalChunksParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelNonterminalChunks, arg.DbTime, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const chainHasLeasedChunks = `-- name: ChainHasLeasedChunks :one
SELECT EXISTS (
    SELECT 1
    FROM chunks
    WHERE job_id = $1
      AND state = 'LEASED'
      AND current_rank_id = $2
      AND current_chain_id = $3
)
`

type ChainHasLeasedChunksParams struct {
	JobID   uuid.UUID   `json:"job_id"`
	RankID  pgtype.UUID `json:"rank_id"`
	ChainID *int64      `json:"chain_id"`
}

func (q *Queries) ChainHasLeasedChunks(ctx context.Context, arg ChainHasLeasedChunksParams) (bool, error) {
	row := q.db.QueryRow(ctx, chainHasLeasedChunks, arg.JobID, arg.RankID, arg.ChainID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const failChunk = `-- name: FailChunk :one
UPDATE chunks
SET state = 'FAILED',
    current_rank_id = NULL,
    current_chain_id = NULL,
    lease_expires_at = NULL,
    retry_count = $1,
    not_before = NULL,
    last_failure_class = $2,
    last_failure_message = $3,
    last_failure_at = $4,
    terminal_at = $4,
    updated_at = $4
WHERE job_id = $5
  AND chunk_id = $6
RETURNING job_id, chunk_id, input_ref, state, current_rank_id, current_chain_id, lease_generation, lease_expires_at, retry_count, not_before, output_uri, output_checksum, output_size_bytes, last_failure_class, last_failure_message, last_failure_at, created_at, updated_at, terminal_at
`

type FailChunkParams struct {
	RetryCount     int32              `json:"retry_count"`
	FailureClass   *string            `json:"failure_class"`
	FailureMessage *string            `json:"failure_message"`
	DbTime         pgtype.Timestamptz `json:"db_time"`
	JobID          uuid.UUID          `json:"job_id"`
	ChunkID        int64              `json:"chunk_id"`
}

func (q *Queries) FailChunk(ctx context.Context, arg FailChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, failChunk,
		arg.RetryCount,
		arg.FailureClass,
		arg.FailureMessage,
		arg.DbTime,
		arg.JobID,
		arg.ChunkID,
	)
	var i Chunk
	err := row.Scan(
		&i.JobID,
		&i.ChunkID,
		&i.InputRef,
		&i.State,
		&i.CurrentRankID,
		&i.CurrentChainID,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NotBefore,
		&i.OutputUri,
		&i.OutputChecksum,
		&i.OutputSizeBytes,
		&i.LastFailureClass,
		&i.LastFailureMessage,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const findClaimCandidates = `-- name: FindClaimCandidates :many
SELECT
    chunks.job_id, chunks.chunk_id, chunks.input_ref, chunks.state, chunks.current_rank_id, chunks.current_chain_id, chunks.lease_generation, chunks.lease_expires_at, chunks.retry_count, chunks.not_before, chunks.output_uri, chunks.output_checksum, chunks.output_size_bytes, chunks.last_failure_class, chunks.last_failure_message, chunks.last_failure_at, chunks.created_at, chunks.updated_at, chunks.terminal_at,
    CASE state
        WHEN 'READY' THEN not_before
        WHEN 'LEASED' THEN lease_expires_at
    END AS eligible_at
FROM chunks
WHERE job_id = $1
  AND (
      (state = 'READY' AND not_before <= $2)
      OR (state = 'LEASED' AND lease_expires_at <= $2)
  )
ORDER BY eligible_at, chunk_id
LIMIT $3
`

type FindClaimCandidatesParams struct {
	JobID          uuid.UUID          `json:"job_id"`
	DiscoveryTime  pgtype.Timestamptz `json:"discovery_time"`
	CandidateLimit int32              `json:"candidate_limit"`
}

type FindClaimCandidatesRow struct {
	JobID              uuid.UUID          `json:"job_id"`
	ChunkID            int64              `json:"chunk_id"`
	InputRef           string             `json:"input_ref"`
	State              ChunkState         `json:"state"`
	CurrentRankID      pgtype.UUID        `json:"current_rank_id"`
	CurrentChainID     *int64             `json:"current_chain_id"`
	LeaseGeneration    int64              `json:"lease_generation"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	RetryCount         int32              `json:"retry_count"`
	NotBefore          pgtype.Timestamptz `json:"not_before"`
	OutputUri          *string            `json:"output_uri"`
	OutputChecksum     *string            `json:"output_checksum"`
	OutputSizeBytes    *int64             `json:"output_size_bytes"`
	LastFailureClass   *string            `json:"last_failure_class"`
	LastFailureMessage *string            `json:"last_failure_message"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
	EligibleAt         interface{}        `json:"eligible_at"`
}

func (q *Queries) FindClaimCandidates(ctx context.Context, arg FindClaimCandidatesParams) ([]FindClaimCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findClaimCandidates, arg.JobID, arg.DiscoveryTime, arg.CandidateLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClaimCandidatesRow{}
	for rows.Next() {
		var i FindClaimCandidatesRow
		if err := rows.Scan(
			&i.JobID,
			&i.ChunkID,
			&i.InputRef,
			&i.State,
			&i.CurrentRankID,
			&i.CurrentChainID,
			&i.LeaseGeneration,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.NotBefore,
			&i.OutputUri,
			&i.OutputChecksum,
			&i.OutputSizeBytes,
			&i.LastFailureClass,
			&i.LastFailureMessage,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
			&i.EligibleAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExpiredDrainingChunkIDs = `-- name: FindExpiredDrainingChunkIDs :many
SELECT chunk_id
FROM chunks
WHERE job_id = $1
  AND state = 'LEASED'
  AND current_rank_id = $2
  AND current_chain_id = $3
  AND lease_expires_at <= $4
ORDER BY chunk_id
LIMIT $5
`

type FindExpiredDrainingChunkIDsParams struct {
	JobID          uuid.UUID          `json:"job_id"`
	RankID         pgtype.UUID        `json:"rank_id"`
	ChainID        *int64             `json:"chain_id"`
	DiscoveryTime  pgtype.Timestamptz `json:"discovery_time"`
	CandidateLimit int32              `json:"candidate_limit"`
}

func (q *Queries) FindExpiredDrainingChunkIDs(ctx context.Context, arg FindExpiredDrainingChunkIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, findExpiredDrainingChunkIDs,
		arg.JobID,
		arg.RankID,
		arg.ChainID,
		arg.DiscoveryTime,
		arg.CandidateLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var chunk_id int64
		if err := rows.Scan(&chunk_id); err != nil {
			return nil, err
		}
		items = append(items, chunk_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChunks = `-- name: GetChunks :many
SELECT job_id, chunk_id, input_ref, state, current_rank_id, current_chain_id, lease_generation, lease_expires_at, retry_count, not_before, output_uri, output_checksum, output_size_bytes, last_failure_class, last_failure_message, last_failure_at, created_at, updated_at, terminal_at
FROM chunks
WHERE job_id = $1
  AND chunk_id = ANY($2::bigint[])
ORDER BY chunk_id
`

type GetChunksParams struct {
	JobID    uuid.UUID `json:"job_id"`
	ChunkIds []int64   `json:"chunk_ids"`
}

func (q *Queries) GetChunks(ctx context.Context, arg GetChunksParams) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, getChunks, arg.JobID, arg.ChunkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.JobID,
			&i.ChunkID,
			&i.InputRef,
			&i.State,
			&i.CurrentRankID,
			&i.CurrentChainID,
			&i.LeaseGeneration,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.NotBefore,
			&i.OutputUri,
			&i.OutputChecksum,
			&i.OutputSizeBytes,
			&i.LastFailureClass,
			&i.LastFailureMessage,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunks = `-- name: InsertChunks :many
INSERT INTO chunks (
    job_id,
    chunk_id,
    input_ref,
    state,
    lease_generation,
    retry_count,
    not_before,
    created_at,
    updated_at
)
SELECT
    $1,
    input.chunk_id,
    input.input_ref,
    'READY',
    0,
    0,
    $2,
    $2,
    $2
FROM (
    SELECT
        chunk.chunk_id,
        ($3::text[])[chunk.ordinality] AS input_ref
    FROM unnest($4::bigint[])
        WITH ORDINALITY AS chunk (chunk_id, ordinality)
) AS input
ORDER BY input.chunk_id
RETURNING chunk_id
`

type InsertChunksParams struct {
	JobID     uuid.UUID          `json:"job_id"`
	DbTime    pgtype.Timestamptz `json:"db_time"`
	InputRefs []string           `json:"input_refs"`
	ChunkIds  []int64            `json:"chunk_ids"`
}

func (q *Queries) InsertChunks(ctx context.Context, arg InsertChunksParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, insertChunks,
		arg.JobID,
		arg.DbTime,
		arg.InputRefs,
		arg.ChunkIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var chunk_id int64
		if err := rows.Scan(&chunk_id); err != nil {
			return nil, err
		}
		items = append(items, chunk_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChunks = `-- name: LockChunks :many
SELECT job_id, chunk_id, input_ref, state, current_rank_id, current_chain_id, lease_generation, lease_expires_at, retry_count, not_before, output_uri, output_checksum, output_size_bytes, last_failure_class, last_failure_message, last_failure_at, created_at, updated_at, terminal_at
FROM chunks
WHERE job_id = $1
  AND chunk_id = ANY($2::bigint[])
ORDER BY chunk_id
FOR UPDATE
`

type LockChunksParams struct {
	JobID    uuid.UUID `json:"job_id"`
	ChunkIds []int64   `json:"chunk_ids"`
}

func (q *Queries) LockChunks(ctx context.Context, arg LockChunksParams) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, lockChunks, arg.JobID, arg.ChunkIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.JobID,
			&i.ChunkID,
			&i.InputRef,
			&i.State,
			&i.CurrentRankID,
			&i.CurrentChainID,
			&i.LeaseGeneration,
			&i.LeaseExpiresAt,
			&i.RetryCount,
			&i.NotBefore,
			&i.OutputUri,
			&i.OutputChecksum,
			&i.OutputSizeBytes,
			&i.LastFailureClass,
			&i.LastFailureMessage,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNonterminalChunks = `-- name: LockNonterminalChunks :many
SELECT chunk_id
FROM chunks
WHERE job_id = $1
  AND state IN ('READY', 'LEASED')
ORDER BY chunk_id
FOR UPDATE
`

func (q *Queries) LockNonterminalChunks(ctx context.Context, jobID uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockNonterminalChunks, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var chunk_id int64
		if err := rows.Scan(&chunk_id); err != nil {
			return nil, err
		}
		items = append(items, chunk_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewMatchingLeases = `-- name: RenewMatchingLeases :many
WITH input AS (
    SELECT
        $6::bigint[] AS chunk_ids,
        $7::bigint[] AS lease_generations
),
requested AS (
    SELECT
        chunk.chunk_id,
        input.lease_generations[chunk.ordinality] AS lease_generation
    FROM input,
         unnest(input.chunk_ids) WITH ORDINALITY AS chunk (chunk_id, ordinality)
)
UPDATE chunks AS chunk
SET lease_expires_at = $1,
    updated_at = $2
FROM requested
WHERE chunk.job_id = $3
  AND chunk.chunk_id = requested.chunk_id
  AND chunk.state = 'LEASED'
  AND chunk.current_rank_id = $4
  AND chunk.current_chain_id = $5
  AND chunk.lease_generation = requested.lease_generation
RETURNING chunk.chunk_id, chunk.lease_generation, chunk.lease_expires_at
`

type RenewMatchingLeasesParams struct {
	LeaseExpiresAt   pgtype.Timestamptz `json:"lease_expires_at"`
	DbTime           pgtype.Timestamptz `json:"db_time"`
	JobID            uuid.UUID          `json:"job_id"`
	RankID           pgtype.UUID        `json:"rank_id"`
	ChainID          *int64             `json:"chain_id"`
	ChunkIds         []int64            `json:"chunk_ids"`
	LeaseGenerations []int64            `json:"lease_generations"`
}

type RenewMatchingLeasesRow struct {
	ChunkID         int64              `json:"chunk_id"`
	LeaseGeneration int64              `json:"lease_generation"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) RenewMatchingLeases(ctx context.Context, arg RenewMatchingLeasesParams) ([]RenewMatchingLeasesRow, error) {
	rows, err := q.db.Query(ctx, renewMatchingLeases,
		arg.LeaseExpiresAt,
		arg.DbTime,
		arg.JobID,
		arg.RankID,
		arg.ChainID,
		arg.ChunkIds,
		arg.LeaseGenerations,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RenewMatchingLeasesRow{}
	for rows.Next() {
		var i RenewMatchingLeasesRow
		if err := rows.Scan(&i.ChunkID, &i.LeaseGeneration, &i.LeaseExpiresAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueExpiredDrainingChunks = `-- name: RequeueExpiredDrainingChunks :many
UPDATE chunks
SET state = 'READY',
    current_rank_id = NULL,
    current_chain_id = NULL,
    lease_expires_at = NULL,
    not_before = $1,
    updated_at = $1
WHERE job_id = $2
  AND chunk_id = ANY($3::bigint[])
  AND state = 'LEASED'
  AND current_rank_id = $4
  AND current_chain_id = $5
  AND lease_expires_at <= $1
RETURNING chunk_id
`

type RequeueExpiredDrainingChunksParams struct {
	DbTime   pgtype.Timestamptz `json:"db_time"`
	JobID    uuid.UUID          `json:"job_id"`
	ChunkIds []int64            `json:"chunk_ids"`
	RankID   pgtype.UUID        `json:"rank_id"`
	ChainID  *int64             `json:"chain_id"`
}

func (q *Queries) RequeueExpiredDrainingChunks(ctx context.Context, arg RequeueExpiredDrainingChunksParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, requeueExpiredDrainingChunks,
		arg.DbTime,
		arg.JobID,
		arg.ChunkIds,
		arg.RankID,
		arg.ChainID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var chunk_id int64
		if err := rows.Scan(&chunk_id); err != nil {
			return nil, err
		}
		items = append(items, chunk_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryChunk = `-- name: RetryChunk :one
UPDATE chunks
SET state = 'READY',
    current_rank_id = NULL,
    current_chain_id = NULL,
    lease_expires_at = NULL,
    retry_count = $1,
    not_before = $2,
    last_failure_class = $3,
    last_failure_message = $4,
    last_failure_at = $5,
    updated_at = $5
WHERE job_id = $6
  AND chunk_id = $7
RETURNING job_id, chunk_id, input_ref, state, current_rank_id, current_chain_id, lease_generation, lease_expires_at, retry_count, not_before, output_uri, output_checksum, output_size_bytes, last_failure_class, last_failure_message, last_failure_at, created_at, updated_at, terminal_at
`

type RetryChunkParams struct {
	RetryCount     int32              `json:"retry_count"`
	NotBefore      pgtype.Timestamptz `json:"not_before"`
	FailureClass   *string            `json:"failure_class"`
	FailureMessage *string            `json:"failure_message"`
	DbTime         pgtype.Timestamptz `json:"db_time"`
	JobID          uuid.UUID          `json:"job_id"`
	ChunkID        int64              `json:"chunk_id"`
}

func (q *Queries) RetryChunk(ctx context.Context, arg RetryChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, retryChunk,
		arg.RetryCount,
		arg.NotBefore,
		arg.FailureClass,
		arg.FailureMessage,
		arg.DbTime,
		arg.JobID,
		arg.ChunkID,
	)
	var i Chunk
	err := row.Scan(
		&i.JobID,
		&i.ChunkID,
		&i.InputRef,
		&i.State,
		&i.CurrentRankID,
		&i.CurrentChainID,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NotBefore,
		&i.OutputUri,
		&i.OutputChecksum,
		&i.OutputSizeBytes,
		&i.LastFailureClass,
		&i.LastFailureMessage,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const succeedChunk = `-- name: SucceedChunk :one
UPDATE chunks
SET state = 'SUCCEEDED',
    current_rank_id = NULL,
    current_chain_id = NULL,
    lease_expires_at = NULL,
    output_uri = $1,
    output_checksum = $2,
    output_size_bytes = $3,
    terminal_at = $4,
    updated_at = $4
WHERE job_id = $5
  AND chunk_id = $6
RETURNING job_id, chunk_id, input_ref, state, current_rank_id, current_chain_id, lease_generation, lease_expires_at, retry_count, not_before, output_uri, output_checksum, output_size_bytes, last_failure_class, last_failure_message, last_failure_at, created_at, updated_at, terminal_at
`

type SucceedChunkParams struct {
	OutputUri       *string            `json:"output_uri"`
	OutputChecksum  *string            `json:"output_checksum"`
	OutputSizeBytes *int64             `json:"output_size_bytes"`
	DbTime          pgtype.Timestamptz `json:"db_time"`
	JobID           uuid.UUID          `json:"job_id"`
	ChunkID         int64              `json:"chunk_id"`
}

func (q *Queries) SucceedChunk(ctx context.Context, arg SucceedChunkParams) (Chunk, error) {
	row := q.db.QueryRow(ctx, succeedChunk,
		arg.OutputUri,
		arg.OutputChecksum,
		arg.OutputSizeBytes,
		arg.DbTime,
		arg.JobID,
		arg.ChunkID,
	)
	var i Chunk
	err := row.Scan(
		&i.JobID,
		&i.ChunkID,
		&i.InputRef,
		&i.State,
		&i.CurrentRankID,
		&i.CurrentChainID,
		&i.LeaseGeneration,
		&i.LeaseExpiresAt,
		&i.RetryCount,
		&i.NotBefore,
		&i.OutputUri,
		&i.OutputChecksum,
		&i.OutputSizeBytes,
		&i.LastFailureClass,
		&i.LastFailureMessage,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}
