// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelJob = `-- name: CancelJob :one
UPDATE jobs
SET state = 'CANCELLED',
    terminal_at = $1,
    updated_at = $1
WHERE job_id = $2
  AND state IN ('PENDING', 'RUNNING')
RETURNING job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
`

type CancelJobParams struct {
	DbTime pgtype.Timestamptz `json:"db_time"`
	JobID  uuid.UUID          `json:"job_id"`
}

func (q *Queries) CancelJob(ctx context.Context, arg CancelJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, cancelJob, arg.DbTime, arg.JobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const countJobChunks = `-- name: CountJobChunks :one
SELECT count(*)
FROM chunks
WHERE job_id = $1
`

func (q *Queries) CountJobChunks(ctx context.Context, jobID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countJobChunks, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    job_id,
    total_chunk_count,
    max_retries,
    retry_backoff_ms,
    lease_duration_ms,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $6
)
RETURNING job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
`

type CreateJobParams struct {
	JobID           uuid.UUID          `json:"job_id"`
	TotalChunkCount int64              `json:"total_chunk_count"`
	MaxRetries      int32              `json:"max_retries"`
	RetryBackoffMs  int64              `json:"retry_backoff_ms"`
	LeaseDurationMs int64              `json:"lease_duration_ms"`
	DbTime          pgtype.Timestamptz `json:"db_time"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.JobID,
		arg.TotalChunkCount,
		arg.MaxRetries,
		arg.RetryBackoffMs,
		arg.LeaseDurationMs,
		arg.DbTime,
	)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const finalizeJobRegistration = `-- name: FinalizeJobRegistration :one
UPDATE jobs
SET state = 'RUNNING',
    registration_completed_at = $1,
    updated_at = $1
WHERE job_id = $2
  AND state = 'PENDING'
RETURNING job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
`

type FinalizeJobRegistrationParams struct {
	DbTime pgtype.Timestamptz `json:"db_time"`
	JobID  uuid.UUID          `json:"job_id"`
}

func (q *Queries) FinalizeJobRegistration(ctx context.Context, arg FinalizeJobRegistrationParams) (Job, error) {
	row := q.db.QueryRow(ctx, finalizeJobRegistration, arg.DbTime, arg.JobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
FROM jobs
WHERE job_id = $1
`

func (q *Queries) GetJob(ctx context.Context, jobID uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const lockJob = `-- name: LockJob :one
SELECT job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
FROM jobs
WHERE job_id = $1
FOR UPDATE
`

func (q *Queries) LockJob(ctx context.Context, jobID uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, lockJob, jobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const recordJobChunkFailed = `-- name: RecordJobChunkFailed :one
UPDATE jobs
SET failed_chunk_count = failed_chunk_count + 1,
    state = CASE
        WHEN succeeded_chunk_count + failed_chunk_count + 1 = total_chunk_count
            THEN 'FAILED'::job_state
        ELSE state
    END,
    terminal_at = CASE
        WHEN succeeded_chunk_count + failed_chunk_count + 1 = total_chunk_count
            THEN $1
        ELSE terminal_at
    END,
    updated_at = $1
WHERE job_id = $2
  AND state = 'RUNNING'
RETURNING job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
`

type RecordJobChunkFailedParams struct {
	DbTime pgtype.Timestamptz `json:"db_time"`
	JobID  uuid.UUID          `json:"job_id"`
}

func (q *Queries) RecordJobChunkFailed(ctx context.Context, arg RecordJobChunkFailedParams) (Job, error) {
	row := q.db.QueryRow(ctx, recordJobChunkFailed, arg.DbTime, arg.JobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}

const recordJobChunkSucceeded = `-- name: RecordJobChunkSucceeded :one
UPDATE jobs
SET succeeded_chunk_count = succeeded_chunk_count + 1,
    state = CASE
        WHEN succeeded_chunk_count + failed_chunk_count + 1 = total_chunk_count
            THEN CASE
                WHEN failed_chunk_count = 0 THEN 'SUCCEEDED'::job_state
                ELSE 'FAILED'::job_state
            END
        ELSE state
    END,
    terminal_at = CASE
        WHEN succeeded_chunk_count + failed_chunk_count + 1 = total_chunk_count
            THEN $1
        ELSE terminal_at
    END,
    updated_at = $1
WHERE job_id = $2
  AND state = 'RUNNING'
RETURNING job_id, state, total_chunk_count, succeeded_chunk_count, failed_chunk_count, max_retries, retry_backoff_ms, lease_duration_ms, created_at, registration_completed_at, updated_at, terminal_at
`

type RecordJobChunkSucceededParams struct {
	DbTime pgtype.Timestamptz `json:"db_time"`
	JobID  uuid.UUID          `json:"job_id"`
}

func (q *Queries) RecordJobChunkSucceeded(ctx context.Context, arg RecordJobChunkSucceededParams) (Job, error) {
	row := q.db.QueryRow(ctx, recordJobChunkSucceeded, arg.DbTime, arg.JobID)
	var i Job
	err := row.Scan(
		&i.JobID,
		&i.State,
		&i.TotalChunkCount,
		&i.SucceededChunkCount,
		&i.FailedChunkCount,
		&i.MaxRetries,
		&i.RetryBackoffMs,
		&i.LeaseDurationMs,
		&i.CreatedAt,
		&i.RegistrationCompletedAt,
		&i.UpdatedAt,
		&i.TerminalAt,
	)
	return i, err
}
