// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChainState string

const (
	ChainStateACTIVE   ChainState = "ACTIVE"
	ChainStateDRAINING ChainState = "DRAINING"
)

func (e *ChainState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChainState(s)
	case string:
		*e = ChainState(s)
	default:
		return fmt.Errorf("unsupported scan type for ChainState: %T", src)
	}
	return nil
}

type NullChainState struct {
	ChainState ChainState `json:"chain_state"`
	Valid      bool       `json:"valid"` // Valid is true if ChainState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChainState) Scan(value interface{}) error {
	if value == nil {
		ns.ChainState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChainState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChainState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChainState), nil
}

type ChunkState string

const (
	ChunkStateREADY     ChunkState = "READY"
	ChunkStateLEASED    ChunkState = "LEASED"
	ChunkStateSUCCEEDED ChunkState = "SUCCEEDED"
	ChunkStateFAILED    ChunkState = "FAILED"
	ChunkStateCANCELLED ChunkState = "CANCELLED"
)

func (e *ChunkState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChunkState(s)
	case string:
		*e = ChunkState(s)
	default:
		return fmt.Errorf("unsupported scan type for ChunkState: %T", src)
	}
	return nil
}

type NullChunkState struct {
	ChunkState ChunkState `json:"chunk_state"`
	Valid      bool       `json:"valid"` // Valid is true if ChunkState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChunkState) Scan(value interface{}) error {
	if value == nil {
		ns.ChunkState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChunkState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChunkState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChunkState), nil
}

type JobState string

const (
	JobStatePENDING   JobState = "PENDING"
	JobStateRUNNING   JobState = "RUNNING"
	JobStateSUCCEEDED JobState = "SUCCEEDED"
	JobStateFAILED    JobState = "FAILED"
	JobStateCANCELLED JobState = "CANCELLED"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState `json:"job_state"`
	Valid    bool     `json:"valid"` // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type Chunk struct {
	JobID              uuid.UUID          `json:"job_id"`
	ChunkID            int64              `json:"chunk_id"`
	InputRef           string             `json:"input_ref"`
	State              ChunkState         `json:"state"`
	CurrentRankID      pgtype.UUID        `json:"current_rank_id"`
	CurrentChainID     *int64             `json:"current_chain_id"`
	LeaseGeneration    int64              `json:"lease_generation"`
	LeaseExpiresAt     pgtype.Timestamptz `json:"lease_expires_at"`
	RetryCount         int32              `json:"retry_count"`
	NotBefore          pgtype.Timestamptz `json:"not_before"`
	OutputUri          *string            `json:"output_uri"`
	OutputChecksum     *string            `json:"output_checksum"`
	OutputSizeBytes    *int64             `json:"output_size_bytes"`
	LastFailureClass   *string            `json:"last_failure_class"`
	LastFailureMessage *string            `json:"last_failure_message"`
	LastFailureAt      pgtype.Timestamptz `json:"last_failure_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TerminalAt         pgtype.Timestamptz `json:"terminal_at"`
}

type Job struct {
	JobID                   uuid.UUID          `json:"job_id"`
	State                   JobState           `json:"state"`
	InputManifestRef        string             `json:"input_manifest_ref"`
	TotalChunkCount         int64              `json:"total_chunk_count"`
	SucceededChunkCount     int64              `json:"succeeded_chunk_count"`
	FailedChunkCount        int64              `json:"failed_chunk_count"`
	MaxRetries              int32              `json:"max_retries"`
	RetryBackoffInitialMs   int64              `json:"retry_backoff_initial_ms"`
	RetryBackoffMaxMs       int64              `json:"retry_backoff_max_ms"`
	LeaseDurationMs         int64              `json:"lease_duration_ms"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	RegistrationCompletedAt pgtype.Timestamptz `json:"registration_completed_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	TerminalAt              pgtype.Timestamptz `json:"terminal_at"`
}

type JobChainAssociation struct {
	JobID      uuid.UUID          `json:"job_id"`
	RankID     uuid.UUID          `json:"rank_id"`
	ChainID    int64              `json:"chain_id"`
	State      ChainState         `json:"state"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	DrainingAt pgtype.Timestamptz `json:"draining_at"`
}
