// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: time.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz
`

func (q *Queries) DatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var column_1 pgtype.Timestamptz
	err := row.Scan(&column_1)
	return column_1, err
}
