---
apiVersion: v1
kind: Service
metadata:
  name: chunk-manager
  namespace: default
  labels:
    app.kubernetes.io/name: chunk-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chunk-manager
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: grpc
      # h2c is HTTP/2 over cleartext TCP (no TLS)
      appProtocol: kubernetes.io/h2c